config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'static_pages/about'

  get 'static_pages/contact'

  resources :sections, only: [:index, :show] do
    resources :costumes, only: [:show]
  end

end

app/models/costume.rb
# == Schema Information
#
# Table name: costumes
#
#  id         :integer          not null, primary key
#  section_id :integer          indexed
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  image_id   :string
#  slug       :string           indexed
#
# Indexes
#
#  index_costumes_on_section_id  (section_id)
#  index_costumes_on_slug        (slug) UNIQUE
#

class Costume < ActiveRecord::Base
  # Pretty URLs using costume names
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Image Uploader
  attachment :image

  # Belongs to a section
  belongs_to :section, inverse_of: :costumes

  # Has many costume variants
  has_many :costume_variants, inverse_of: :costume
end

app/models/costume_variant.rb
# == Schema Information
#
# Table name: costume_variants
#
#  id          :integer          not null, primary key
#  costume_id  :integer          indexed
#  name        :string
#  gender      :string
#  open        :boolean
#  sold_out    :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  price_cents :integer
#  slug        :string           indexed
#
# Indexes
#
#  index_costume_variants_on_costume_id  (costume_id)
#  index_costume_variants_on_slug        (slug) UNIQUE
#

class CostumeVariant < ActiveRecord::Base
  # Pretty URLs using costume variant names
  extend FriendlyId
  friendly_id :name, use: :slugged

  # Monetize Price Attribute
  monetize :price_cents

  # Belongs to one costume
  belongs_to :costume, inverse_of: :costume_variants

  # May have one or many images
  has_many :costume_variant_images, inverse_of: :costume_variant, dependent: :destroy
end

app/models/costume_variant_image.rb
# == Schema Information
#
# Table name: costume_variant_images
#
#  id                 :integer          not null, primary key
#  file_id            :string
#  description        :string
#  costume_variant_id :integer          indexed
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
# Indexes
#
#  index_costume_variant_images_on_costume_variant_id  (costume_variant_id)
#

class CostumeVariantImage < ActiveRecord::Base
  # Image Uploader
  attachment :file

  # Belongs to a costume variant
  belongs_to :costume_variant, inverse_of: :costume_variant_images
end

app/models/section.rb
# == Schema Information
#
# Table name: sections
#
#  id           :integer          not null, primary key
#  section_name :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  image_id     :string
#  slug         :string           indexed
#
# Indexes
#
#  index_sections_on_slug  (slug) UNIQUE
#

class Section < ActiveRecord::Base
  # Pretty URLs using section names
  extend FriendlyId
  friendly_id :section_name, use: :slugged

  # Image Uploader
  attachment :image

  # Has many costumes
  has_many :costumes, -> {order(:name)}, inverse_of: :section
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  def show
    @costume = Costume.includes(:section, :costume_variants).find(params[:id])
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.order(:section_name)
  end

  def show
    @section = Section.friendly.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costumes_helper.rb
module CostumesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/costumes/_costume_variant.html.erb
<div class="panel costume-variant">
  <div class="panel-heading" role="tab" id="Heading<%= costume_variant.id %>">
    <h4 class="panel-title">
      <a role="button" data-toggle="collapse" data-parent="#costume-variants-container" href="#Variant<%= costume_variant.id %>" aria-expanded="true" aria-controls="Variant<%= costume_variant.id %>">
        <%= costume_variant.name %>
      </a>
    </h4>
  </div>
  <div id="Variant<%= costume_variant.id %>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="Heading<%= costume_variant.id %>">
    <div class="panel-body">
      <div class="row">
        <%= render partial: 'costumes/costume_variant_image', collection: costume_variant.costume_variant_images %>
      </div>
    </div>
  </div>
</div>

app/views/costumes/_costume_variant_image.html.erb
<div class="costume-variant-image col-xs-12 col-sm-6 col-md-4 col-lg-3">
    <%= link_to(attachment_image_tag(costume_variant_image, :file, :limit, 400, nil, {alt: "#{costume_variant_image.costume_variant} Variant Image", class: 'img-responsive fancybox', rel: "gallery#{costume_variant_image.costume_variant.id}"}), attachment_url(costume_variant_image, :file), class: 'thumbnail') %>
</div>

app/views/costumes/show.html.erb
<%
   @pagetitle = "#{@costume.section.section_name}: #{@costume.name}"
   @page_class = 'costumes show'
%>

<div class="container-fluid">
  <header class="text-center">
    <%= image_tag 'wee-own-logo.png', alt: 'Celebrating Wee Own Logo' %>
    <h1 class="title"><%= @costume.section.section_name %>: <%= @costume.name %></h1>
  </header>
  <div class="content panel-group" id="costume-variants-container" role="tablist" aria-multiselectable="true">
    <%= render partial: 'costumes/costume_variant', collection: @costume.costume_variants %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Jus Wee &amp; Friends - <%= @pagetitle %></title>

  <%= stylesheet_link_tag    'application', media: 'all' %>

  <%= csrf_meta_tags %>
</head>
    <body id="interface-container" class="user-interface <%= @page_class %>" style="<%= @background_css %>">

        <%= yield %>

        <%= render partial: 'shared/user_nav' %>

    </body>
    <%= javascript_include_tag 'application' %>
</html>

app/views/sections/_costume.html.erb
<div class="costume col-xs-12 col-sm-6 col-md-4 col-lg-3">
  <%= link_to(attachment_image_tag(costume, :image, :limit, 400, nil, {alt: costume.name, class: 'img-responsive'}), section_costume_path(costume.section_id, costume), class: 'thumbnail') %>
  <div class="overlay">
    <div class="overlay-bg"></div>
    <div class="section-title"><p><%= costume.name %></p></div>
  </div>
</div>

app/views/sections/_section.html.erb
<div class="section col-xs-12 col-sm-6 col-md-4 col-lg-3">
  <%= link_to(attachment_image_tag(section, :image, :limit, 400, nil, {alt: section.section_name }), section_path(section), class: 'thumbnail') %>
  <div class="overlay">
    <div class="overlay-bg"></div>
    <div class="section-title"><p><%= section.section_name %></p></div>
  </div>
</div>

app/views/sections/index.html.erb
<%
   @pagetitle = 'Sections for 2016'
   @page_class = 'sections index'
%>

<div class="container-fluid">
  <header class="text-center">
    <%= image_tag 'wee-own-logo.png', width: 150, alt: 'Celebrating Wee Own Logo' %>
    <h1 class="title">Sections for 2016</h1>
  </header>
  <div id="sections-content" class="content text-center center-block">
    <div class="row">
      <%= render @sections %>
    </div>
  </div>
</div>

app/views/sections/show.html.erb
<%
   @pagetitle = @section.section_name
   @page_class = 'sections show'
%>

<div class="container-fluid">
  <header class="text-center">
    <%= image_tag 'wee-own-logo.png', alt: 'Celebrating Wee Own Logo' %>
    <h1 class="title"><%= @section.section_name %></h1>
  </header>
  <div class="well well-sm content">
    <div class="row">
      <%= render partial: 'sections/costume', collection: @section.costumes %>
    </div>
  </div>
</div>

app/views/shared/_user_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-bottom navbar-inverse" id="site-nav-bar">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if @page_class == 'static home-page' %>
            <a id="nav-bar-title" class="navbar-brand" href="#">Just Wee &amp; Friends</a>
        <% else %>
            <%= link_to(image_tag('juswee-logo.png', height: 25), '#', class: 'navbar-brand', id: 'nav-bar-logo') %>
        <% end %>
      </div>

      <div class="collapse navbar-collapse" id="main-nav">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Home', '#' %></li>
          <li><%= link_to 'About Us', '#' %></li>
          <li><%= link_to 'Sections', '#' %></li>
          <li><%= link_to 'Registration', '#' %></li>
          <li><%= link_to 'Contact Us', '#' %></li>
          <li><%= link_to 'Facebook', 'https://www.facebook.com/justfriendstt' %></li>
        </ul>
      </div>
    </div>
</nav>

app/views/static_pages/about.html.erb
<%
   @pagetitle = 'About Us'
   @page_class = 'static about-page'
%>

<div class="container-fluid">
  <header>
    <!-- TODO Insert Brand Image -->
    <h1 class="title text-center">About Us</h1>
  </header>
  <div id="about-content" class="text-center center-block">
    <p>The Band &quot;Just Friends&quot; was launched in 2009 after a group of friends Earl Crosby, Anne-Marie Placide, Dune Ali and Chris Humphrey came together to play mas like we used to in the Olden Days.
      We felt that true masqueraders had become disenchanted with the new carnival experience of  Big Bands, very expensive costumes, music for the gym and long periods of just standing around in the band.</p>
    <p>&quot;Just Friends&quot; responded to this cry and judging from all the positive feedback, our masqueraders enjoyed a fantastic experience.</p>
    <p>Our Goal is to keep the band to a manageable size so the friends of &quot;Just Friends&quot; and their friends can continue to simply have a great time.</p>
    <p>We have already initiated a series of affordable events where we can all come together to listen to music, dance or simply socialize from time to time. We have tried to be creative in the planning of these events,
      and our clients have really enjoyed themselves. In fact we are the first to have a party dancing to live DVD’s</p>
    <p>We will continue to forge ahead in our effort to truly entertain our Friends.</p>
  </div>
</div>

app/views/static_pages/contact.html.erb
<%
   @pagetitle = 'Contact Us'
   @page_class = 'static contact-page'
%>

<div class="container-fluid">
  <header>
    <!-- TODO Insert Brand Image -->
    <h1 class="title text-center">Contact Us</h1>
  </header>
  <div id="about-content" class="row text-center center-block">
    <div class="col-xs-12 col-sm-12 col-md-6">
      <h2>Registration @ Crosby's Music Center</h2>
          <address>
            <p>
                54 Western Main Road, St. James<br/>
                <abbr title="Phone">P:</abbr> (868) 622-7622<br/>
            </p>
          </address>
      <p>
        <u>Hours</u><br/>
        Monday - Friday; 4pm - 7pm<br/>
        Saturday; 10am - 4pm
      </p>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6">
      <h2>Information</h2>
      <p>
        <em>For all information, contact: </em><br/>
        Anne-Marie Placide: (868) 765-7725<br/>
        Earl Crosby: (868) 680-7383<br/>
        Chris Humphrey: (868) 680-7995<br/>
      </p>
      <p><strong>For international enquiries</strong>, contact (305) 848-2901</p>
      <p><a href="mailto:contact@justfriendstt.com">contact@justfriendstt.com</a></p>
    </div>
  </div>
  <div class="clearfix"></div>
</div>

app/views/static_pages/home.html.erb
<%
   @pagetitle = 'Welcome to Celebrating Wee Own | Carnival Presentation 2016'
   @page_class = 'static home-page'
%>

<div class="container-fluid">
  <div class="col-xs-12 col-sm-12 col-md-4">
    <div id="juswee-logo" class="center-block text-center">
      <%= image_tag 'juswee-logo.png', width: 400, alt: 'Jus Wee and Friends', class: 'img-responsive' %>
    </div>
    <div class="text text-center" id="presentation-text">
      <p>Carnival 2016<br/>Presentation</p>
    </div>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-4">
    <div class="logo center-block text-center">
      <%= image_tag 'wee-own-logo.png', width: 500, alt: 'Celebrating Wee Own', class: 'img-responsive' %>
    </div>
  </div>
  <div class="clearfix"></div>
</div>